kitty.conf remove regular match
mrjones2014/smart-splits.nvim pull request #148
Opened 2024-01-17 16:19 UTC by nanmoumou

#147 ability to optimize environmental recognition

2024-01-18 12:20 UTC, mrjones2014 requested changes

2024-01-18 12:20 UTC, mrjones2014 commented on kitty/pass_keys.py
> +# from kitty.keys import keyboard_mode_name
remove commented out line

2024-01-18 12:20 UTC, mrjones2014 commented on kitty/pass_keys.py
> +
unneeded newline

2024-01-18 12:20 UTC, mrjones2014 commented on kitty/pass_keys.py
> +        boss.active_tab.resize_window("taller", amount)
looks like these lines came from different formatter settings. please revert for a clean diff.

2024-01-18 12:20 UTC, mrjones2014 commented on kitty/pass_keys.py
> +    if cmd[-4:] == "nvim":
correct me if I'm wrong but I don't think this works if, for example, you run `nvim ./some/file/name.txt` or if you run Neovim via a `vim` shell alias.

2024-01-18 12:20 UTC, mrjones2014 commented on kitty/pass_keys.py
> +    elif action == "relative_resize":
please revert formatting changes for a clean diff.

2024-01-25 14:28 UTC, mrjones2014 commented
Hi @nanmoumou just wondering if you're planning to update the PR

2024-01-27 02:19 UTC, nanmoumou commented
> 你好@nanmoumou只是想知道您是否打算更新 PR

Give it up for now.
I've found a small issue where I can't seem to get the correct results when using pipenv, with or without regular expressions.

2024-01-27 02:23 UTC, closed without merging